# Generated by Django 5.0.4 on 2024-05-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'employee')], default=1, max_length=50),
        ),
    ]
