# Generated by Django 5.0.4 on 2024-05-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0003_alter_customuser_user_type_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
