# Generated by Django 5.0.4 on 2024-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0004_alter_employees_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='employees',
            name='empcode',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='employees',
            name='empdept',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='empdesignation',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='employees',
            name='joiningdate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
