# Generated by Django 4.2.3 on 2024-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0007_alter_customuser_user_type_alter_employees_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'employee')], default=1, max_length=50),
        ),
    ]
