# Generated by Django 4.2.3 on 2024-05-09 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0009_alter_customuser_user_type_alter_empeducation_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empexperience',
            name='empid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
