# Generated by Django 5.0.4 on 2024-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0010_alter_empexperience_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'employee')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='empcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
