# Generated by Django 4.1.7 on 2024-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0011_alter_customuser_user_type_alter_employees_empcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'employee'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='empcode',
            field=models.CharField(max_length=20),
        ),
    ]
