# Generated by Django 5.2.8 on 2026-03-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0012_alter_customuser_user_type_alter_employees_empcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('study_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('previous_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assignments_submitted', models.PositiveIntegerField(default=0)),
                ('extracurricular_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('study_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assignments_submitted', models.PositiveIntegerField(default=0)),
                ('extracurricular_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_outcome', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ersapp.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
