# Generated by Django 5.2.8 on 2026-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersapp', '0013_studentprofile_predictionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/user.png', upload_to='profile_pic'),
        ),
    ]
